apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth
          image: ss-auth-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:root@postgres:5433/authdb"
            - name: PORT
              value: "8081"
            - name: TOKEN_EXPIRY
              value: "3600"               
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          command: [ "sh", "-c" ]
          args:
            - sleep 5 && npm run prisma:deploy && npm run prisma:seed && npm run start
          volumeMounts:
            - name: jwt-keys
              mountPath: /app/keys
              readOnly: true
      volumes:
        - name: jwt-keys
          secret:
            secretName: jwt-keys
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081
