apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: audit-service
  labels:
    app: audit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  serviceName: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
        - name: audit-service
          image: ss-audit-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
          env:
            - name: KAFKA_BROKERS
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: CLIENT_ID
              value: "audit-service"
            - name: GROUP_ID
              value: "audit-group"
          volumeMounts:
            - name: audit-logs
              mountPath: /app/logs
      volumes:
        - name: audit-logs
          persistentVolumeClaim:
            claimName: audit-logs-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audit-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: audit-service
  labels:
    app: audit-service
spec:
  ports:
    - port: 8086
      targetPort: 8086
  selector:
    app: audit-service